services:
  db:
    image: postgres:17-alpine
    container_name: bountybeacon-db
    environment:
      POSTGRES_DB: bountybeacon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bountybeacon-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bountybeacon
      DB_USER: postgres
      DB_PASSWORD: postgres
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      H1_USERNAME: ${H1_USERNAME}
      H1_API_KEY: ${H1_API_KEY}
      BC_API_KEY: ${BC_API_KEY}
      INT_API_KEY: ${INT_API_KEY}
    ports:
      - "8080:8080"

volumes:
  pgdata:
