spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/bountybeacon
  logging:
    level:
      com.bountybeacon: DEBUG
  flyway:
    enabled: true
    baseline-on-migrate: true

provider:
  hackerone:
    username: ${H1_USERNAME:your-hackerone-username}
    api-key: ${H1_API_KEY: your-api-key}
  bugcrowd:
    api-key: ${BC_API_KEY: your-api-key}
  intigriti:
    api-key: your-api-key}

notification:
  discord:
    webhook-url: ${DISCORD_WEBHOOK_URL:"https://discord.com/api/webhooks/....."}