spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5436/bountybeacon
  logging:
    level:
      com.bountybeacon: DEBUG
  flyway:
    enabled: true
    baseline-on-migrate: true
